[package]
name = "nt-sysdump"
version = "0.1.0"
edition = "2024"

[features]
default = ["static"]
no_std = []
static = ["phf"]

[dependencies.phf]
version = "0.13.1"
optional = true
default-features = false
features = ["macros"]

[dependencies.windows-sys]
version = "0.61.2"
features = [
    "Win32_Foundation",
    "Win32_Storage_FileSystem",
    "Win32_System_WindowsProgramming",
    "Win32_System_SystemInformation",
    "Win32_System_Diagnostics_Debug",
    "Win32_System_SystemServices",
    "Win32_System_LibraryLoader",
    "Win32_System_Threading",
    "Win32_System_Kernel",
]

[target.'cfg(windows)'.dependencies]
ntapi = "0.4.1"
aligned = "0.4.2"

[lib]
name = "nt_sysdump"
path = "src/lib.rs"

[[bin]]
name = "nt_sysdump"
path = "src/main.rs"

[profile.dev]
panic = "abort"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false
overflow-checks = false
incremental = false
